language: python
python:
  - "2.7"
install:
  - python setup.py install
  - pip install psycopg2
  - pip install flake8
  - pip install coveralls
script:
  - coverage run setup.py test
  - python setup.py test_on_postgres
  - flake8 .
after_success:
  coveralls
