language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install git+ssh://git@github.com/openlabs/nereid-activity-stream.git@develop
  - python setup.py install
  - pip install flake8
script:
  - python setup.py test
  - flake8 .
