language: python
python:
  - "2.6"
  - "2.7"
install:
  - python setup.py install
  - pip install psycopg2
  - pip install flake8
script:
  - python setup.py test
  - python setup.py test_on_postgres
  - flake8 .
